// <auto-generated />
using System;
using FoodDiary.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDiary.Api.Migrations
{
    [DbContext(typeof(FoodDiaryDbContext))]
    [Migration("20260617202257_AddFoodCategoryToFoodAlternative")]
    partial class AddFoodCategoryToFoodAlternative
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodDiary.Api.Models.FoodAlternative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FoodCategory")
                        .HasColumnType("text");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeeklyFrequency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FoodAlternatives");
                });

            modelBuilder.Entity("FoodDiary.Api.Models.PlannedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("FoodAlternativeId")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyPlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodAlternativeId");

                    b.HasIndex("WeeklyPlanId");

                    b.ToTable("PlannedMeals");
                });

            modelBuilder.Entity("FoodDiary.Api.Models.WeeklyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("FoodDiary.Api.Models.PlannedMeal", b =>
                {
                    b.HasOne("FoodDiary.Api.Models.FoodAlternative", "FoodAlternative")
                        .WithMany()
                        .HasForeignKey("FoodAlternativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDiary.Api.Models.WeeklyPlan", "WeeklyPlan")
                        .WithMany("PlannedMeals")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodAlternative");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("FoodDiary.Api.Models.WeeklyPlan", b =>
                {
                    b.Navigation("PlannedMeals");
                });
#pragma warning restore 612, 618
        }
    }
}
